'use client'

import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { AlertCircle } from 'lucide-react'
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'

export function AttentionAlert() {
  const [isOpen, setIsOpen] = useState(true)
  const [showFullMessage, setShowFullMessage] = useState(false)

  if (!isOpen) return null

  return (
    <AnimatePresence>
      <motion.div
        initial={{ opacity: 0, y: 50 }}
        animate={{ opacity: 1, y: 0 }}
        exit={{ opacity: 0, y: 50 }}
        transition={{ type: 'spring', stiffness: 300, damping: 30 }}
        className="fixed bottom-4 right-4 z-50"
      >
        <Alert 
          variant="default" 
          className="w-64 cursor-pointer"
          onClick={() => setShowFullMessage(!showFullMessage)}
        >
          <AlertCircle className="h-4 w-4" />
          <AlertTitle>Attention</AlertTitle>
          <AlertDescription>
            {showFullMessage ? (
              "These results are generated by an LLM, and therefore can be inconsistent. If you are unhappy with the result, simply try pressing analyze again."
            ) : (
              "Click for important information"
            )}
          </AlertDescription>
        </Alert>
      </motion.div>
    </AnimatePresence>
  )
}

