"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import SentenceDisplay from "./SentenceDisplay"
import { useToast } from "@/components/ui/use-toast"

interface SentenceInputProps {
  onSubmit: (sentence: string, llmResponse: any) => Promise<void>
  onCancel: () => void
  selectedLanguage: string
}

export default function SentenceInput({ onSubmit, onCancel, selectedLanguage }: SentenceInputProps) {
  const [sentence, setSentence] = useState("")
  const [processedSentence, setProcessedSentence] = useState(null)
  const [isLoading, setIsLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const { toast } = useToast()

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setIsLoading(true)
    setError(null)

    try {
      const response = await fetch("/api/process-sentence", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ sentence, language: selectedLanguage }),
      })

      const data = await response.json()

      if (!response.ok) {
        throw new Error(data.error || "Failed to process sentence")
      }

      setProcessedSentence(data)
      await onSubmit(sentence, data)
      onCancel()

      toast({
        title: "Sentence Analyzed",
        description:
          "The sentence has been processed successfully. Results may be inconsistent as they are generated by an LLM.",
        duration: 5000,
      })
    } catch (error) {
      console.error("Error processing sentence:", error)
      setError(error instanceof Error ? error.message : "An unknown error occurred")
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <div className="bg-background p-6 rounded-lg shadow-lg">
      <form onSubmit={handleSubmit} className="space-y-4">
        <p className="text-sm text-muted-foreground">
          Type a sentence in {selectedLanguage} to analyze its grammar
        </p>
        <Input
          type="text"
          value={sentence}
          onChange={(e) => setSentence(e.target.value)}
          placeholder="Enter a sentence"
          className="mb-4"
        />
        <div className="flex gap-2">
          <Button type="submit" disabled={isLoading}>
            {isLoading ? "Processing..." : "Analyze"}
          </Button>
          <Button type="button" variant="outline" onClick={onCancel}>
            Cancel
          </Button>
        </div>
      </form>
      {error && (
        <Alert variant="destructive" className="mt-4">
          <AlertTitle>Error</AlertTitle>
          <AlertDescription>{error}</AlertDescription>
        </Alert>
      )}
      {isLoading && (
        <Alert className="mt-4">
          <AlertTitle>Processing</AlertTitle>
          <AlertDescription>Analyzing your sentence. This may take a few moments.</AlertDescription>
        </Alert>
      )}
      {processedSentence && <SentenceDisplay data={processedSentence} />}
    </div>
  )
}

