"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import SentenceDisplay from "./SentenceDisplay"
import ErrorDisplay from "./ErrorDisplay"
import { useToast } from "@/components/ui/use-toast"
import { analyze } from "@/lib/grammario-client"
import { transformAnalysisToLLMResponse, extractErrorsAndTeaching } from "@/lib/grammario-transform"

interface SentenceInputProps {
  onSubmit: (sentence: string, llmResponse: any, analysisMetadata?: any) => Promise<void>
  onCancel: () => void
  selectedLanguage: string
}

export default function SentenceInput({ onSubmit, onCancel, selectedLanguage }: SentenceInputProps) {
  const [sentence, setSentence] = useState("")
  const [processedSentence, setProcessedSentence] = useState<any>(null)
  const [isLoading, setIsLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [rawResponse, setRawResponse] = useState<string | null>(null)
  const [analysisMetadata, setAnalysisMetadata] = useState<{
    errors: any[]
    teaching_notes: any[]
    normalized?: string
    language?: string
    tokens?: any[]
  } | null>(null)
  const { toast } = useToast()

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setIsLoading(true)
    setError(null)
    setRawResponse(null)

    try {
      // Use the new robust analysis system
      const analysis = await analyze(sentence, selectedLanguage)
      
      // Transform to the format expected by the UI
      const transformedData = transformAnalysisToLLMResponse(analysis)
      
      // Extract error and teaching information
      const metadata = extractErrorsAndTeaching(analysis)
      
      setProcessedSentence(transformedData)
      setAnalysisMetadata(metadata)
      await onSubmit(sentence, transformedData, metadata)
      onCancel()

      toast({
        title: "Sentence Analyzed",
        description:
          "The sentence has been processed successfully. Results may be inconsistent as they are generated by an LLM.",
        duration: 5000,
      })
    } catch (error) {
      console.error("Error processing sentence:", error)
      setError(error instanceof Error ? error.message : "An unknown error occurred")
      setRawResponse(null) // Clear any previous raw response
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <div className="bg-background p-6 rounded-lg shadow-lg">
      <form onSubmit={handleSubmit} className="space-y-4">
        <p className="text-sm text-muted-foreground">
          Type a sentence in {selectedLanguage} to analyze its grammar
        </p>
        <Input
          type="text"
          value={sentence}
          onChange={(e) => setSentence(e.target.value)}
          placeholder="Enter a sentence"
          className="mb-4"
        />
        <div className="flex gap-2">
          <Button type="submit" disabled={isLoading}>
            {isLoading ? "Processing..." : "Analyze"}
          </Button>
          <Button type="button" variant="outline" onClick={onCancel}>
            Cancel
          </Button>
        </div>
      </form>
      {error && (
        <Alert variant="destructive" className="mt-4">
          <AlertTitle>Error</AlertTitle>
          <AlertDescription>
            {error}
            {rawResponse && (
              <div className="mt-2">
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => {
                    const blob = new Blob([rawResponse], { type: 'text/plain' });
                    const url = URL.createObjectURL(blob);
                    const a = document.createElement('a');
                    a.href = url;
                    a.download = 'llm-response.txt';
                    document.body.appendChild(a);
                    a.click();
                    document.body.removeChild(a);
                    URL.revokeObjectURL(url);
                  }}
                >
                  View Raw LLM Output
                </Button>
              </div>
            )}
          </AlertDescription>
        </Alert>
      )}
      {isLoading && (
        <Alert className="mt-4">
          <AlertTitle>Processing</AlertTitle>
          <AlertDescription>Analyzing your sentence. This may take a few moments.</AlertDescription>
        </Alert>
      )}
      {processedSentence && (
        <>
          <SentenceDisplay 
            data={processedSentence} 
            title="Analyzed Sentence"
            sentence={sentence}
          />
          {analysisMetadata && (
            <ErrorDisplay
              errors={analysisMetadata.errors}
              teachingNotes={analysisMetadata.teaching_notes}
              originalSentence={sentence}
              normalizedSentence={analysisMetadata.normalized}
              tokens={analysisMetadata.tokens}
            />
          )}
        </>
      )}
    </div>
  )
}

